version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: 'test_db123'
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'test_database'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:4.7.5
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8081:8081'
    volumes:
      - ./src/:/go/src
    tty: true
