version: "3.9"

services:
  mysql:
    image: mysql:5.7
    container_name: "test_db123"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "test_database"
      MYSQL_HOST: "test_db123"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    volumes:
      - ./database/sql/:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./src/:/go/src
    tty: true
